server:
  address:     ":8000"
  openapiPath: "/api.json"
  swaggerPath: "/swagger"

logger:
  level : "all"
  stdout: true
database:
  default:
    type:  "mysql"
    link:  "root:123456@tcp(127.0.0.1:3306)/gf"

# database:
#   default:
#     host:          "127.0.0.1"
#     port:          "3306"
#     user:          "root"
#     pass:          "12345678"
#     name:          "test"
#     type:          "mysql"
#     role:          "master"
#     debug:         "true"
#     dryrun:        0
#     weight:        "100"
#     prefix:        "gf_"
#     charset:       "utf8"
#     timezone:      "local"
#     maxIdle:       "10"
#     maxOpen:       "100"
#     maxLifetime:   "30s"

gfcli:
  gen:
    dao:
    - link:     "mysql:root:123456@tcp(127.0.0.1:3306)/gf"
      tables:   ""
      jsonCase: "CamelLower"
